---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-13.10

suites:
  - name: default
    run_list:
      - recipe[dynamodb-local::default]
    attributes:
